name: gam_app
description: Governmental Access Model.

dependencies:
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+4
  firebase_auth: ^0.14.0+5
  flutter_datetime_picker: ^1.2.6
  path_provider: ^1.3.0
  flutter_html_to_pdf: ^0.5.2
  email_validator: '^1.0.0'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/full-bloom.png
    - assets/images/mountains.jpeg
    - assets/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf