import 'package:gam_app/CountryPicker/country.dart';

List<String> _countryList = [
  "أندورا",
  "الإمارات العربية المتحدة",
  "أفغانستان",
  "أنتيغوا وبربودا",
  "أنغيلا",
  "ألبانيا",
  "أرمينيا",
  "جزر الأنتيل الهولندية",
  "أنغولا",
  "أنتاركتيكا",
  "الأرجنتين",
  "ساموا الأمريكية",
  "النمسا",
  "أستراليا",
  "أروبا",
  "جزر آلاند",
  "أذربيجان",
  "البوسنة والهرسك",
  "بربادوس",
  "بنغلاديش",
  "بلجيكا",
  "بوركينا فاسو",
  "بلغاريا",
  "البحرين",
  "بوروندي",
  "بنين",
  "سانت بارتيليمي",
  "برمودا",
  "بروناي دار السلام",
  "بوليفيا , دولة متعددة القوميات",
  "هولندا الكاريبية",
  "البرازيل"
      "الباهاما"
      "بوتان",
  "جزيرة بوفيت",
  "بوتسوانا",
  "روسيا البيضاء",
  "بليز",
  "كندا",
  "جزر كوكوس (كيلينغ)",
  "جمهورية الكونغو الديمقراطية",
  "جمهورية افريقيا الوسطى",
  "الكونغو",
  "سويسرا",
  "كوت ديفوار",
  "جزر كوك",
  "تشيلي",
  "الكاميرون",
  "الصين",
  "كولومبيا",
  "كوستا ريكا",
  "كوبا",
  "الرأس الأخضر",
  "كوراساو",
  "جزيرة كريسماس",
  "قبرص",
  "جمهورية التشيك",
  "ألمانيا",
  "جيبوتي",
  "الدنمارك",
  "دومينيكا",
  "جمهورية الدومنيكان",
  "الجزائر",
  "الاكوادور",
  "استونيا",
  "مصر",
  "الصحراء الغربية",
  "إريتريا",
  "إسبانيا",
  "أثيوبيا",
  "فنلندا",
  "فيجي",
  "جزر فوكلاند (مالفيناس)",
  "ميكرونيزيا , ولايات الموحدة",
  "جزر فاروس",
  "فرنسا",
  "الغابون",
  "المملكة المتحدة",
  "إنكلترا",
  "إيرلندا الشمالية",
  "اسكتلندا",
  "ويلز",
  "غرينادا",
  "جورجيا",
  "غيانا الفرنسية",
  "غيرنسي",
  "غانا",
  "جبل طارق",
  "الأرض الخضراء",
  "غامبيا",
  "غينيا",
  "جوادلوب",
  "غينيا الإستوائية",
  "اليونان",
  "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
  "غواتيمالا",
  "غوام",
  "غينيا بيساو",
  "غيانا",
  "هونج كونج",
  "قلب الجزيرة وجزر ماكدونالز",
  "هندوراس",
  "كرواتيا",
  "هايتي",
  "هنغاريا",
  "إندونيسيا",
  "ايرلندا",
  "إسرائيل",
  "جزيرة آيل أوف مان",
  "الهند",
  "إقليم المحيط البريطاني الهندي",
  "العراق",
  "جمهورية إيران الإسلامية",
  "أيسلندا",
  "إيطاليا",
  "جيرسي",
  "جامايكا",
  "الأردن",
  "اليابان",
  "كينيا",
  "قيرغيزستان",
  "كمبوديا",
  "كيريباس",
  "جزر القمر",
  "سانت كيتس ونيفيس",
  "كوريا, الجمهورية الشعبية الديمقراطية",
  "جمهورية كوريا",
  "الكويت",
  "جزر كايمان",
  "كازاخستان",
  "جمهورية لاو الديمقراطية الشعبية",
  "لبنان",
  "القديسة لوسيا",
  "ليختنشتاين",
  "سيريلانكا",
  "ليبيريا",
  "ليسوتو",
  "ليتوانيا",
  "لوكسمبورغ",
  "لاتفيا",
  "ليبيا",
  "المغرب",
  "موناكو",
  "جمهورية مولدوفا",
  "الجبل الأسود",
  "القديس مارتن",
  "مدغشقر",
  "جزر مارشال",
  "مقدونيا , جمهورية يوغوسلافيا السابقة",
  "مالي",
  "ميانمار",
  "منغوليا",
  "ماكاو",
  "جزر مريانا الشمالية",
  "مارتينيك",
  "موريتانيا",
  "مونتسيرات",
  "مالطا",
  "موريشيوس",
  "جزر المالديف",
  "ملاوي",
  "المكسيك",
  "ماليزيا",
  "موزمبيق",
  "ناميبيا",
  "كاليدونيا الجديدة",
  "النيجر",
  "جزيرة نورفولك",
  "نيجيريا",
  "نيكاراغوا",
  "هولندا",
  "النرويج",
  "نيبال",
  "ناورو",
  "نيوي",
  "نيوزيلاندا",
  "سلطنة عمان",
  "بنما",
  "بيرو",
  "بولينيزيا الفرنسية",
  "بابوا غينيا الجديدة",
  "الفلبين",
  "باكستان",
  "بولندا",
  "سانت بيير وميكلون"
      "بيتكيرن",
  "بورتوريكو",
  "فلسطين",
  "البرتغال",
  "بالاو",
  "باراغواي",
  "دولة قطر",
  "جمع شمل",
  "رومانيا",
  "صربيا",
  "الاتحاد الروسي",
  "رواندا",
  "المملكة العربية السعودية",
  "جزر سليمان",
  "سيشيل",
  "السودان",
  "السويد"
      "سنغافورة",
  "سانت هيلانة , أسينشن وتريستان دا كونها",
  "سلوفينيا",
  "جزر سفالبارد وجان ماين",
  "سلوفاكيا",
  "سيرا ليون",
  "سان مارينو",
  "السنغال",
  "الصومال",
  "سورينام",
  "جنوب السودان",
  "سان تومي وبرينسيبي",
  "السلفادور",
  "سينت مارتن (الجزء الهولندي)",
  "الجمهورية العربية السورية",
  "سوازيلاند",
  "جزر تركس وكايكوس",
  "تشاد",
  "المناطق الجنوبية لفرنسا",
  "توجو",
  "تايلاند",
  "طاجيكستان",
  "توكيلاو",
  "تيمور الشرقية",
  "تركمانستان",
  "تونس",
  "تونغا",
  "ديك رومي",
  "ترينداد وتوباغو",
  "توفالو",
  "تايوان",
  "جمهورية تنزانيا المتحدة",
  "أوكرانيا",
  "أوغندا",
  "جزر الولايات المتحدة البعيدة الصغيرة",
  "الولايات المتحدة الأمريكية",
  "أوروغواي",
  "أوزبكستان",
  "الكرسي الرسولي (دولة الفاتيكان)",
  "سانت فنسنت وجزر غرينادين",
  "جمهورية فنزويلا البوليفارية",
  "جزر العذراء البريطانية",
  "جزر فيرجن , الولايات المتحدة",
  "فيتنام",
  "فانواتو",
  "جزر واليس وفوتونا",
  "كوسوفو",
  "ساموا",
  "اليمن",
  "مايوت",
  "جنوب أفريقيا",
  "زامبيا",
  "زيمبابوي"
];

final List<Country> countryList = [
  Country(
    isoCode: "AD",
    phoneCode: "376",
    name: _countryList[0],
    iso3Code: "AND",
  ),
  Country(
    isoCode: "AE",
    phoneCode: "971",
    name: _countryList[1],
    iso3Code: "ARE",
  ),
  Country(
    isoCode: "AF",
    phoneCode: "93",
    name: _countryList[2],
    iso3Code: "AFG",
  ),
  Country(
    isoCode: "AG",
    phoneCode: "1-268",
    name: _countryList[3],
    iso3Code: "ATG",
  ),
  Country(
    isoCode: "AI",
    phoneCode: "1-264",
    name: _countryList[4],
    iso3Code: "AIA",
  ),
  Country(
    isoCode: "AL",
    phoneCode: "355",
    name: _countryList[5],
    iso3Code: "ALB",
  ),
  Country(
    isoCode: "AM",
    phoneCode: "374",
    name: _countryList[6],
    iso3Code: "ARM",
  ),
  Country(
    isoCode: "AN",
    phoneCode: "599",
    name: _countryList[7],
    iso3Code: "AN",
  ),
  Country(
    isoCode: "AO",
    phoneCode: "244",
    name: _countryList[8],
    iso3Code: "AGO",
  ),
  Country(
    isoCode: "AQ",
    phoneCode: "672",
    name: _countryList[9],
    iso3Code: "ATA",
  ),
  Country(
    isoCode: "AR",
    phoneCode: "54",
    name: _countryList[10],
    iso3Code: "ARG",
  ),
  Country(
    isoCode: "AS",
    phoneCode: "1-684",
    name: _countryList[11],
    iso3Code: "ASM",
  ),
  Country(
    isoCode: "AT",
    phoneCode: "43",
    name: _countryList[12],
    iso3Code: "AUT",
  ),
  Country(
    isoCode: "AU",
    phoneCode: "61",
    name: _countryList[13],
    iso3Code: "AUS",
  ),
  Country(
    isoCode: "AW",
    phoneCode: "297",
    name: _countryList[14],
    iso3Code: "ABW",
  ),
  Country(
    isoCode: "AX",
    phoneCode: "358",
    name: _countryList[15],
    iso3Code: "ALA",
  ),
  Country(
    isoCode: "AZ",
    phoneCode: "994",
    name: _countryList[16],
    iso3Code: "AZE",
  ),
  Country(
    isoCode: "BA",
    phoneCode: "387",
    name: _countryList[17],
    iso3Code: "BIH",
  ),
  Country(
    isoCode: "BB",
    phoneCode: "1-246",
    name: _countryList[18],
    iso3Code: "BRB",
  ),
  Country(
    isoCode: "BD",
    phoneCode: "880",
    name: _countryList[19],
    iso3Code: "BGD",
  ),
  Country(
    isoCode: "BE",
    phoneCode: "32",
    name: _countryList[20],
    iso3Code: "BEL",
  ),
  Country(
    isoCode: "BF",
    phoneCode: "226",
    name: _countryList[21],
    iso3Code: "BFA",
  ),
  Country(
    isoCode: "BG",
    phoneCode: "359",
    name: _countryList[22],
    iso3Code: "BGR",
  ),
  Country(
    isoCode: "BH",
    phoneCode: "973",
    name: _countryList[23],
    iso3Code: "BHR",
  ),
  Country(
    isoCode: "BI",
    phoneCode: "257",
    name: _countryList[24],
    iso3Code: "BDI",
  ),
  Country(
    isoCode: "BJ",
    phoneCode: "229",
    name: _countryList[25],
    iso3Code: "BEN",
  ),
  Country(
    isoCode: "BL",
    phoneCode: "590",
    name: _countryList[26],
    iso3Code: "BLM",
  ),
  Country(
    isoCode: "BM",
    phoneCode: "1-441",
    name: _countryList[27],
    iso3Code: "BMU",
  ),
  Country(
    isoCode: "BN",
    phoneCode: "673",
    name: _countryList[28],
    iso3Code: "BRN",
  ),
  Country(
    isoCode: "BO",
    phoneCode: "591",
    name: _countryList[29],
    iso3Code: "BOL",
  ),
  Country(
    isoCode: "BQ",
    phoneCode: "599",
    name: _countryList[30],
    iso3Code: "BES",
  ),
  Country(
    isoCode: "BR",
    phoneCode: "55",
    name: _countryList[31],
    iso3Code: "BRA",
  ),
  Country(
    isoCode: "BS",
    phoneCode: "1-242",
    name: _countryList[32],
    iso3Code: "BHS",
  ),
  Country(
    isoCode: "BT",
    phoneCode: "975",
    name: _countryList[33],
    iso3Code: "BTN",
  ),
  Country(
    isoCode: "BV",
    phoneCode: "47",
    name: _countryList[34],
    iso3Code: "BVT",
  ),
  Country(
    isoCode: "BW",
    phoneCode: "267",
    name: _countryList[35],
    iso3Code: "BWA",
  ),
  Country(
    isoCode: "BY",
    phoneCode: "375",
    name: _countryList[36],
    iso3Code: "BLR",
  ),
  Country(
    isoCode: "BZ",
    phoneCode: "501",
    name: _countryList[37],
    iso3Code: "BLZ",
  ),
  Country(
    isoCode: "CA",
    phoneCode: "1",
    name: _countryList[38],
    iso3Code: "CAN",
  ),
  Country(
    isoCode: "CC",
    phoneCode: "61",
    name: _countryList[39],
    iso3Code: "CCK",
  ),
  Country(
    isoCode: "CD",
    phoneCode: "243",
    name: _countryList[40],
    iso3Code: "COD",
  ),
  Country(
    isoCode: "CF",
    phoneCode: "236",
    name: _countryList[41],
    iso3Code: "CAF",
  ),
  Country(
    isoCode: "CG",
    phoneCode: "242",
    name: _countryList[42],
    iso3Code: "COG",
  ),
  Country(
    isoCode: "CH",
    phoneCode: "41",
    name: _countryList[43],
    iso3Code: "CHE",
  ),
  Country(
    isoCode: "CI",
    phoneCode: "225",
    name: _countryList[44],
    iso3Code: "CIV",
  ),
  Country(
    isoCode: "CK",
    phoneCode: "682",
    name: _countryList[45],
    iso3Code: "COK",
  ),
  Country(
    isoCode: "CL",
    phoneCode: "56",
    name: _countryList[46],
    iso3Code: "CHL",
  ),
  Country(
    isoCode: "CM",
    phoneCode: "237",
    name: _countryList[47],
    iso3Code: "CMR",
  ),
  Country(
    isoCode: "CN",
    phoneCode: "86",
    name: _countryList[48],
    iso3Code: "CHN",
  ),
  Country(
    isoCode: "CO",
    phoneCode: "57",
    name: _countryList[49],
    iso3Code: "COL",
  ),
  Country(
    isoCode: "CR",
    phoneCode: "506",
    name: _countryList[50],
    iso3Code: "CRI",
  ),
  Country(
    isoCode: "CU",
    phoneCode: "53",
    name: _countryList[51],
    iso3Code: "CUB",
  ),
  Country(
    isoCode: "CV",
    phoneCode: "238",
    name: _countryList[52],
    iso3Code: "CPV",
  ),
  Country(
    isoCode: "CW",
    phoneCode: "599",
    name: _countryList[53],
    iso3Code: "CUW",
  ),
  Country(
    isoCode: "CX",
    phoneCode: "61",
    name: _countryList[54],
    iso3Code: "CXR",
  ),
  Country(
    isoCode: "CY",
    phoneCode: "357",
    name: _countryList[55],
    iso3Code: "CYP",
  ),
  Country(
    isoCode: "CZ",
    phoneCode: "420",
    name: _countryList[56],
    iso3Code: "CZE",
  ),
  Country(
    isoCode: "DE",
    phoneCode: "49",
    name: _countryList[57],
    iso3Code: "DEU",
  ),
  Country(
    isoCode: "DJ",
    phoneCode: "253",
    name: _countryList[58],
    iso3Code: "DJI",
  ),
  Country(
    isoCode: "DK",
    phoneCode: "45",
    name: _countryList[59],
    iso3Code: "DNK",
  ),
  Country(
    isoCode: "DM",
    phoneCode: "1-767",
    name: _countryList[60],
    iso3Code: "DMA",
  ),
  Country(
    isoCode: "DO",
    phoneCode: "1-849",
    name: _countryList[61],
    iso3Code: "DOM",
  ),
  Country(
    isoCode: "DZ",
    phoneCode: "213",
    name: _countryList[62],
    iso3Code: "DZA",
  ),
  Country(
    isoCode: "EC",
    phoneCode: "593",
    name: _countryList[63],
    iso3Code: "ECU",
  ),
  Country(
    isoCode: "EE",
    phoneCode: "372",
    name: _countryList[64],
    iso3Code: "EST",
  ),
  Country(
    isoCode: "EG",
    phoneCode: "20",
    name: _countryList[65],
    iso3Code: "EGY",
  ),
  Country(
    isoCode: "EH",
    phoneCode: "212",
    name: _countryList[66],
    iso3Code: "ESH",
  ),
  Country(
    isoCode: "ER",
    phoneCode: "291",
    name: _countryList[67],
    iso3Code: "ERI",
  ),
  Country(
    isoCode: "ES",
    phoneCode: "34",
    name: _countryList[68],
    iso3Code: "ESP",
  ),
  Country(
    isoCode: "ET",
    phoneCode: "251",
    name: _countryList[69],
    iso3Code: "ETH",
  ),
  Country(
    isoCode: "FI",
    phoneCode: "358",
    name: _countryList[70],
    iso3Code: "FIN",
  ),
  Country(
    isoCode: "FJ",
    phoneCode: "679",
    name: _countryList[71],
    iso3Code: "FJI",
  ),
  Country(
    isoCode: "FK",
    phoneCode: "500",
    name: _countryList[72],
    iso3Code: "FLK",
  ),
  Country(
    isoCode: "FM",
    phoneCode: "691",
    name: _countryList[73],
    iso3Code: "FSM",
  ),
  Country(
    isoCode: "FO",
    phoneCode: "298",
    name: _countryList[74],
    iso3Code: "FRO",
  ),
  Country(
    isoCode: "FR",
    phoneCode: "33",
    name: _countryList[75],
    iso3Code: "FRA",
  ),
  Country(
    isoCode: "GA",
    phoneCode: "241",
    name: _countryList[76],
    iso3Code: "GAB",
  ),
  Country(
    isoCode: "GB",
    phoneCode: "44",
    name: _countryList[77],
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "GB-ENG",
    phoneCode: "44",
    name: _countryList[78],
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "GB-NIR",
    phoneCode: "44",
    name: _countryList[79],
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "GB-SCT",
    phoneCode: "44",
    name: _countryList[80],
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "GB-WLS",
    phoneCode: "44",
    name: _countryList[81],
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "GD",
    phoneCode: "1-473",
    name: _countryList[82],
    iso3Code: "GRD",
  ),
  Country(
    isoCode: "GE",
    phoneCode: "995",
    name: _countryList[83],
    iso3Code: "GEO",
  ),
  Country(
    isoCode: "GF",
    phoneCode: "594",
    name: _countryList[84],
    iso3Code: "GUF",
  ),
  Country(
    isoCode: "GG",
    phoneCode: "44-1481",
    name: _countryList[85],
    iso3Code: "GGY",
  ),
  Country(
    isoCode: "GH",
    phoneCode: "233",
    name: _countryList[86],
    iso3Code: "GHA",
  ),
  Country(
    isoCode: "GI",
    phoneCode: "350",
    name: _countryList[87],
    iso3Code: "GIB",
  ),
  Country(
    isoCode: "GL",
    phoneCode: "299",
    name: _countryList[88],
    iso3Code: "GRL",
  ),
  Country(
    isoCode: "GM",
    phoneCode: "220",
    name: _countryList[89],
    iso3Code: "GMB",
  ),
  Country(
    isoCode: "GN",
    phoneCode: "224",
    name: _countryList[90],
    iso3Code: "GIN",
  ),
  Country(
    isoCode: "GP",
    phoneCode: "590",
    name: _countryList[91],
    iso3Code: "GLP",
  ),
  Country(
    isoCode: "GQ",
    phoneCode: "240",
    name: _countryList[92],
    iso3Code: "GNQ",
  ),
  Country(
    isoCode: "GR",
    phoneCode: "30",
    name: _countryList[93],
    iso3Code: "GRC",
  ),
  Country(
    isoCode: "GS",
    phoneCode: "500",
    name: _countryList[94],
    iso3Code: "SGS",
  ),
  Country(
    isoCode: "GT",
    phoneCode: "502",
    name: _countryList[95],
    iso3Code: "GTM",
  ),
  Country(
    isoCode: "GU",
    phoneCode: "1-671",
    name: _countryList[96],
    iso3Code: "GUM",
  ),
  Country(
    isoCode: "GW",
    phoneCode: "245",
    name: _countryList[97],
    iso3Code: "GNB",
  ),
  Country(
    isoCode: "GY",
    phoneCode: "592",
    name: _countryList[98],
    iso3Code: "GUY",
  ),
  Country(
    isoCode: "HK",
    phoneCode: "852",
    name: _countryList[99],
    iso3Code: "HKG",
  ),
  Country(
    isoCode: "HM",
    phoneCode: "672",
    name: _countryList[100],
    iso3Code: "HMD",
  ),
  Country(
    isoCode: "HN",
    phoneCode: "504",
    name: _countryList[101],
    iso3Code: "HND",
  ),
  Country(
    isoCode: "HR",
    phoneCode: "385",
    name: _countryList[102],
    iso3Code: "HRV",
  ),
  Country(
    isoCode: "HT",
    phoneCode: "509",
    name: _countryList[103],
    iso3Code: "HTI",
  ),
  Country(
    isoCode: "HU",
    phoneCode: "36",
    name: _countryList[104],
    iso3Code: "HUN",
  ),
  Country(
    isoCode: "ID",
    phoneCode: "62",
    name: _countryList[105],
    iso3Code: "IDN",
  ),
  Country(
    isoCode: "IE",
    phoneCode: "353",
    name: _countryList[106],
    iso3Code: "IRL",
  ),
  Country(
    isoCode: "IL",
    phoneCode: "972",
    name: _countryList[107],
    iso3Code: "ISR",
  ),
  Country(
    isoCode: "IM",
    phoneCode: "44-1624",
    name: _countryList[108],
    iso3Code: "IMN",
  ),
  Country(
    isoCode: "IN",
    phoneCode: "91",
    name: _countryList[109],
    iso3Code: "IND",
  ),
  Country(
    isoCode: "IO",
    phoneCode: "246",
    name: _countryList[110],
    iso3Code: "IOT",
  ),
  Country(
    isoCode: "IQ",
    phoneCode: "964",
    name: _countryList[111],
    iso3Code: "IRQ",
  ),
  Country(
    isoCode: "IR",
    phoneCode: "98",
    name: _countryList[112],
    iso3Code: "IRN",
  ),
  Country(
    isoCode: "IS",
    phoneCode: "354",
    name: _countryList[113],
    iso3Code: "ISL",
  ),
  Country(
    isoCode: "IT",
    phoneCode: "39",
    name: _countryList[114],
    iso3Code: "ITA",
  ),
  Country(
    isoCode: "JE",
    phoneCode: "44-1534",
    name: _countryList[115],
    iso3Code: "JEY",
  ),
  Country(
    isoCode: "JM",
    phoneCode: "1-876",
    name: _countryList[116],
    iso3Code: "JAM",
  ),
  Country(
    isoCode: "JO",
    phoneCode: "962",
    name: _countryList[117],
    iso3Code: "JOR",
  ),
  Country(
    isoCode: "JP",
    phoneCode: "81",
    name: _countryList[118],
    iso3Code: "JPN",
  ),
  Country(
    isoCode: "KE",
    phoneCode: "254",
    name: _countryList[119],
    iso3Code: "KEN",
  ),
  Country(
    isoCode: "KG",
    phoneCode: "996",
    name: _countryList[120],
    iso3Code: "KGZ",
  ),
  Country(
    isoCode: "KH",
    phoneCode: "855",
    name: _countryList[121],
    iso3Code: "KHM",
  ),
  Country(
    isoCode: "KI",
    phoneCode: "686",
    name: _countryList[122],
    iso3Code: "KIR",
  ),
  Country(
    isoCode: "KM",
    phoneCode: "269",
    name: _countryList[123],
    iso3Code: "COM",
  ),
  Country(
    isoCode: "KN",
    phoneCode: "1-869",
    name: _countryList[124],
    iso3Code: "KNA",
  ),
  Country(
    isoCode: "KP",
    phoneCode: "850",
    name: _countryList[125],
    iso3Code: "PRK",
  ),
  Country(
    isoCode: "KR",
    phoneCode: "82",
    name: _countryList[126],
    iso3Code: "KOR",
  ),
  Country(
    isoCode: "KW",
    phoneCode: "965",
    name: _countryList[127],
    iso3Code: "KWT",
  ),
  Country(
    isoCode: "KY",
    phoneCode: "1-345",
    name: _countryList[128],
    iso3Code: "CYM",
  ),
  Country(
    isoCode: "KZ",
    phoneCode: "7",
    name: _countryList[129],
    iso3Code: "KAZ",
  ),
  Country(
    isoCode: "LA",
    phoneCode: "",
    name: _countryList[130],
    iso3Code: "LAO",
  ),
  Country(
    isoCode: "LB",
    phoneCode: "961",
    name: _countryList[131],
    iso3Code: "LBN",
  ),
  Country(
    isoCode: "LC",
    phoneCode: "1-758",
    name: _countryList[132],
    iso3Code: "LCA",
  ),
  Country(
    isoCode: "LI",
    phoneCode: "423",
    name: _countryList[133],
    iso3Code: "LIE",
  ),
  Country(
    isoCode: "LK",
    phoneCode: "94",
    name: _countryList[134],
    iso3Code: "LKA",
  ),
  Country(
    isoCode: "LR",
    phoneCode: "231",
    name: _countryList[135],
    iso3Code: "LBR",
  ),
  Country(
    isoCode: "LS",
    phoneCode: "266",
    name: _countryList[136],
    iso3Code: "LSO",
  ),
  Country(
    isoCode: "LT",
    phoneCode: "370",
    name: _countryList[137],
    iso3Code: "LTU",
  ),
  Country(
    isoCode: "LU",
    phoneCode: "352",
    name: _countryList[138],
    iso3Code: "LUX",
  ),
  Country(
    isoCode: "LV",
    phoneCode: "371",
    name: _countryList[139],
    iso3Code: "LVA",
  ),
  Country(
    isoCode: "LY",
    phoneCode: "218",
    name: _countryList[140],
    iso3Code: "LBY",
  ),
  Country(
    isoCode: "MA",
    phoneCode: "212",
    name: _countryList[141],
    iso3Code: "MAR",
  ),
  Country(
    isoCode: "MC",
    phoneCode: "377",
    name: _countryList[142],
    iso3Code: "MCO",
  ),
  Country(
    isoCode: "MD",
    phoneCode: "373",
    name: _countryList[143],
    iso3Code: "MDA",
  ),
  Country(
    isoCode: "ME",
    phoneCode: "382",
    name: _countryList[144],
    iso3Code: "MNE",
  ),
  Country(
    isoCode: "MF",
    phoneCode: "590",
    name: _countryList[145],
    iso3Code: "MAF",
  ),
  Country(
    isoCode: "MG",
    phoneCode: "261",
    name: _countryList[146],
    iso3Code: "MDG",
  ),
  Country(
    isoCode: "MH",
    phoneCode: "692",
    name: _countryList[147],
    iso3Code: "MHL",
  ),
  Country(
    isoCode: "MK",
    phoneCode: "389",
    name: _countryList[148],
    iso3Code: "MKD",
  ),
  Country(
    isoCode: "ML",
    phoneCode: "223",
    name: _countryList[149],
    iso3Code: "MLI",
  ),
  Country(
    isoCode: "MM",
    phoneCode: "95",
    name: _countryList[150],
    iso3Code: "MMR",
  ),
  Country(
    isoCode: "MN",
    phoneCode: "976",
    name: _countryList[151],
    iso3Code: "MNG",
  ),
  Country(
    isoCode: "MO",
    phoneCode: "853",
    name: _countryList[152],
    iso3Code: "MAC",
  ),
  Country(
    isoCode: "MP",
    phoneCode: "1-670",
    name: _countryList[153],
    iso3Code: "MNP",
  ),
  Country(
    isoCode: "MQ",
    phoneCode: "596",
    name: _countryList[154],
    iso3Code: "MTQ",
  ),
  Country(
    isoCode: "MR",
    phoneCode: "222",
    name: _countryList[155],
    iso3Code: "MRT",
  ),
  Country(
    isoCode: "MS",
    phoneCode: "1-664",
    name: _countryList[156],
    iso3Code: "MSR",
  ),
  Country(
    isoCode: "MT",
    phoneCode: "356",
    name: _countryList[157],
    iso3Code: "MLT",
  ),
  Country(
    isoCode: "MU",
    phoneCode: "230",
    name: _countryList[158],
    iso3Code: "MUS",
  ),
  Country(
    isoCode: "MV",
    phoneCode: "960",
    name: _countryList[159],
    iso3Code: "MDV",
  ),
  Country(
    isoCode: "MW",
    phoneCode: "265",
    name: _countryList[160],
    iso3Code: "MWI",
  ),
  Country(
    isoCode: "MX",
    phoneCode: "52",
    name: _countryList[161],
    iso3Code: "MEX",
  ),
  Country(
    isoCode: "MY",
    phoneCode: "60",
    name: _countryList[162],
    iso3Code: "MYS",
  ),
  Country(
    isoCode: "MZ",
    phoneCode: "258",
    name: _countryList[163],
    iso3Code: "MOZ",
  ),
  Country(
    isoCode: "NA",
    phoneCode: "264",
    name: _countryList[164],
    iso3Code: "NAM",
  ),
  Country(
    isoCode: "NC",
    phoneCode: "687",
    name: _countryList[165],
    iso3Code: "NCL",
  ),
  Country(
    isoCode: "NE",
    phoneCode: "227",
    name: _countryList[166],
    iso3Code: "NER",
  ),
  Country(
    isoCode: "NF",
    phoneCode: "672",
    name: _countryList[167],
    iso3Code: "NFK",
  ),
  Country(
    isoCode: "NG",
    phoneCode: "234",
    name: _countryList[168],
    iso3Code: "NGA",
  ),
  Country(
    isoCode: "NI",
    phoneCode: "505",
    name: _countryList[169],
    iso3Code: "NIC",
  ),
  Country(
    isoCode: "NL",
    phoneCode: "31",
    name: _countryList[170],
    iso3Code: "NLD",
  ),
  Country(
    isoCode: "NO",
    phoneCode: "47",
    name: _countryList[171],
    iso3Code: "NOR",
  ),
  Country(
    isoCode: "NP",
    phoneCode: "977",
    name: _countryList[172],
    iso3Code: "NPL",
  ),
  Country(
    isoCode: "NR",
    phoneCode: "674",
    name: _countryList[173],
    iso3Code: "NRU",
  ),
  Country(
    isoCode: "NU",
    phoneCode: "683",
    name: _countryList[174],
    iso3Code: "NIU",
  ),
  Country(
    isoCode: "NZ",
    phoneCode: "64",
    name: _countryList[175],
    iso3Code: "NZL",
  ),
  Country(
    isoCode: "OM",
    phoneCode: "968",
    name: _countryList[176],
    iso3Code: "OMN",
  ),
  Country(
    isoCode: "PA",
    phoneCode: "507",
    name: _countryList[177],
    iso3Code: "PAN",
  ),
  Country(
    isoCode: "PE",
    phoneCode: "51",
    name: _countryList[178],
    iso3Code: "PER",
  ),
  Country(
    isoCode: "PF",
    phoneCode: "689",
    name: _countryList[179],
    iso3Code: "PYF",
  ),
  Country(
    isoCode: "PG",
    phoneCode: "675",
    name: _countryList[180],
    iso3Code: "PNG",
  ),
  Country(
    isoCode: "PH",
    phoneCode: "63",
    name: _countryList[181],
    iso3Code: "PHL",
  ),
  Country(
    isoCode: "PK",
    phoneCode: "92",
    name: _countryList[182],
    iso3Code: "PAK",
  ),
  Country(
    isoCode: "PL",
    phoneCode: "48",
    name: _countryList[183],
    iso3Code: "POL",
  ),
  Country(
    isoCode: "PM",
    phoneCode: "508",
    name: _countryList[184],
    iso3Code: "SPM",
  ),
  Country(
    isoCode: "PN",
    phoneCode: "64",
    name: _countryList[185],
    iso3Code: "PCN",
  ),
  Country(
    isoCode: "PR",
    phoneCode: "1-787",
    name: _countryList[186],
    iso3Code: "PRI",
  ),
  Country(
    isoCode: "PS",
    phoneCode: "970",
    name: _countryList[187],
    iso3Code: "PSE",
  ),
  Country(
    isoCode: "PT",
    phoneCode: "351",
    name: _countryList[188],
    iso3Code: "PRT",
  ),
  Country(
    isoCode: "PW",
    phoneCode: "680",
    name: _countryList[189],
    iso3Code: "PLW",
  ),
  Country(
    isoCode: "PY",
    phoneCode: "595",
    name: _countryList[190],
    iso3Code: "PRY",
  ),
  Country(
    isoCode: "QA",
    phoneCode: "974",
    name: _countryList[191],
    iso3Code: "QAT",
  ),
  Country(
    isoCode: "RE",
    phoneCode: "262",
    name: _countryList[192],
    iso3Code: "REU",
  ),
  Country(
    isoCode: "RO",
    phoneCode: "40",
    name: _countryList[193],
    iso3Code: "ROU",
  ),
  Country(
    isoCode: "RS",
    phoneCode: "381",
    name: _countryList[194],
    iso3Code: "SRB",
  ),
  Country(
    isoCode: "RU",
    phoneCode: "7",
    name: _countryList[195],
    iso3Code: "RUS",
  ),
  Country(
    isoCode: "RW",
    phoneCode: "250",
    name: _countryList[196],
    iso3Code: "RWA",
  ),
  Country(
    isoCode: "SA",
    phoneCode: "966",
    name: _countryList[197],
    iso3Code: "SAU",
  ),
  Country(
    isoCode: "SB",
    phoneCode: "677",
    name: _countryList[198],
    iso3Code: "SLB",
  ),
  Country(
    isoCode: "SC",
    phoneCode: "248",
    name: _countryList[199],
    iso3Code: "SYC",
  ),
  Country(
    isoCode: "SD",
    phoneCode: "249",
    name: _countryList[200],
    iso3Code: "SDN",
  ),
  Country(
    isoCode: "SE",
    phoneCode: "46",
    name: _countryList[201],
    iso3Code: "SWE",
  ),
  Country(
    isoCode: "SG",
    phoneCode: "65",
    name: _countryList[202],
    iso3Code: "SGP",
  ),
  Country(
    isoCode: "SH",
    phoneCode: "290",
    name: _countryList[203],
    iso3Code: "SHN",
  ),
  Country(
    isoCode: "SI",
    phoneCode: "386",
    name: _countryList[204],
    iso3Code: "SVN",
  ),
  Country(
    isoCode: "SJ",
    phoneCode: "47",
    name: _countryList[205],
    iso3Code: "SJM",
  ),
  Country(
    isoCode: "SK",
    phoneCode: "421",
    name: _countryList[206],
    iso3Code: "SVK",
  ),
  Country(
    isoCode: "SL",
    phoneCode: "232",
    name: _countryList[207],
    iso3Code: "SLE",
  ),
  Country(
    isoCode: "SM",
    phoneCode: "378",
    name: _countryList[208],
    iso3Code: "SMR",
  ),
  Country(
    isoCode: "SN",
    phoneCode: "221",
    name: _countryList[209],
    iso3Code: "SEN",
  ),
  Country(
    isoCode: "SO",
    phoneCode: "252",
    name: _countryList[210],
    iso3Code: "SOM",
  ),
  Country(
    isoCode: "SR",
    phoneCode: "597",
    name: _countryList[211],
    iso3Code: "SUR",
  ),
  Country(
    isoCode: "SS",
    phoneCode: "211",
    name: _countryList[212],
    iso3Code: "SSD",
  ),
  Country(
    isoCode: "ST",
    phoneCode: "239",
    name: _countryList[213],
    iso3Code: "STP",
  ),
  Country(
    isoCode: "SV",
    phoneCode: "503",
    name: _countryList[214],
    iso3Code: "SLV",
  ),
  Country(
    isoCode: "SX",
    phoneCode: "1-721",
    name: _countryList[215],
    iso3Code: "SXM",
  ),
  Country(
    isoCode: "SY",
    phoneCode: "963",
    name: _countryList[216],
    iso3Code: "SYR",
  ),
  Country(
    isoCode: "SZ",
    phoneCode: "268",
    name: _countryList[217],
    iso3Code: "SWZ",
  ),
  Country(
    isoCode: "TC",
    phoneCode: "1-649",
    name: _countryList[218],
    iso3Code: "TCA",
  ),
  Country(
    isoCode: "TD",
    phoneCode: "235",
    name: _countryList[219],
    iso3Code: "TCD",
  ),
  Country(
    isoCode: "TF",
    phoneCode: "262",
    name: _countryList[220],
    iso3Code: "ATF",
  ),
  Country(
    isoCode: "TG",
    phoneCode: "228",
    name: _countryList[221],
    iso3Code: "TGO",
  ),
  Country(
    isoCode: "TH",
    phoneCode: "66",
    name: _countryList[222],
    iso3Code: "THA",
  ),
  Country(
    isoCode: "TJ",
    phoneCode: "992",
    name: _countryList[223],
    iso3Code: "TJK",
  ),
  Country(
    isoCode: "TK",
    phoneCode: "690",
    name: _countryList[224],
    iso3Code: "TKL",
  ),
  Country(
    isoCode: "TL",
    phoneCode: "670",
    name: _countryList[225],
    iso3Code: "TLS",
  ),
  Country(
    isoCode: "TM",
    phoneCode: "993",
    name: _countryList[226],
    iso3Code: "TKM",
  ),
  Country(
    isoCode: "TN",
    phoneCode: "216",
    name: _countryList[227],
    iso3Code: "TUN",
  ),
  Country(
    isoCode: "TO",
    phoneCode: "676",
    name: _countryList[228],
    iso3Code: "TON",
  ),
  Country(
    isoCode: "TR",
    phoneCode: "90",
    name: _countryList[229],
    iso3Code: "TUR",
  ),
  Country(
    isoCode: "TT",
    phoneCode: "1-868",
    name: _countryList[230],
    iso3Code: "TTO",
  ),
  Country(
    isoCode: "TV",
    phoneCode: "688",
    name: _countryList[231],
    iso3Code: "TUV",
  ),
  Country(
    isoCode: "TW",
    phoneCode: "886",
    name: _countryList[232],
    iso3Code: "TWN",
  ),
  Country(
    isoCode: "TZ",
    phoneCode: "255",
    name: _countryList[233],
    iso3Code: "TZA",
  ),
  Country(
    isoCode: "UA",
    phoneCode: "380",
    name: _countryList[234],
    iso3Code: "UKR",
  ),
  Country(
    isoCode: "UG",
    phoneCode: "256",
    name: _countryList[235],
    iso3Code: "UGA",
  ),
  Country(
    isoCode: "UM",
    phoneCode: "1",
    name: _countryList[236],
    iso3Code: "UMI",
  ),
  Country(
    isoCode: "US",
    phoneCode: "1",
    name: _countryList[237],
    iso3Code: "USA",
  ),
  Country(
    isoCode: "UY",
    phoneCode: "598",
    name: _countryList[238],
    iso3Code: "URY",
  ),
  Country(
    isoCode: "UZ",
    phoneCode: "998",
    name: _countryList[239],
    iso3Code: "UZB",
  ),
  Country(
    isoCode: "VA",
    phoneCode: "379",
    name: _countryList[240],
    iso3Code: "VAT",
  ),
  Country(
    isoCode: "VC",
    phoneCode: "1-784",
    name: _countryList[241],
    iso3Code: "VCT",
  ),
  Country(
    isoCode: "VE",
    phoneCode: "58",
    name: _countryList[242],
    iso3Code: "VEN",
  ),
  Country(
    isoCode: "VG",
    phoneCode: "1-284",
    name: _countryList[243],
    iso3Code: "VGB",
  ),
  Country(
    isoCode: "VI",
    phoneCode: "1-340",
    name: _countryList[244],
    iso3Code: "VIR",
  ),
  Country(
    isoCode: "VN",
    phoneCode: "84",
    name: _countryList[245],
    iso3Code: "VNM",
  ),
  Country(
    isoCode: "VU",
    phoneCode: "678",
    name: _countryList[246],
    iso3Code: "VUT",
  ),
  Country(
    isoCode: "WF",
    phoneCode: "681",
    name: _countryList[247],
    iso3Code: "WLF",
  ),
  Country(
    isoCode: "XK",
    phoneCode: "383",
    name: _countryList[248],
    iso3Code: "KOS",
  ),
  Country(
    isoCode: "WS",
    phoneCode: "685",
    name: _countryList[249],
    iso3Code: "WSM",
  ),
  Country(
    isoCode: "YE",
    phoneCode: "967",
    name: _countryList[250],
    iso3Code: "YEM",
  ),
  Country(
    isoCode: "YT",
    phoneCode: "262",
    name: _countryList[251],
    iso3Code: "MYT",
  ),
  Country(
    isoCode: "ZA",
    phoneCode: "27",
    name: _countryList[252],
    iso3Code: "ZAF",
  ),
  Country(
    isoCode: "ZM",
    phoneCode: "260",
    name: _countryList[253],
    iso3Code: "ZMB",
  ),
  Country(
    isoCode: "ZW",
    phoneCode: "263",
    name: _countryList[254],
    iso3Code: "ZWE",
  ),
];
